
#define SOUND_EFFECT_INFO_POS_X         8
#define SOUND_EFFECT_INFO_POS_Y         3
#define SOUND_EFFECT_INFO_WIDTH         26
#define SOUND_EFFECT_INFO_HEIGHT        15
#define SOUND_EFFECT_INFO_SCREEN_POS    40*SOUND_EFFECT_INFO_POS_Y + SOUND_EFFECT_INFO_POS_X

